name: "Digital Ocean Droplets ip address"
description: "Get the ips for droplets by using tage"
inputs:
  droplet-tag: # id of input
    description: "The tag assined to droplets."
    required: true
    default: "dapi"

  digitalocean-access-token: # id of input
    description: "Digital ocean access_token from the API section"
    required: true
    default: ""

outputs:
  ip_addresses: # id of output
    description: "A list of ips for the any found droplets"
runs:
  using: "node16"
  main: "dist/index.js"
